--EXCEPCIONES
/*
CAPTURA DE ERRORES Y CÓMO ACTUAR ANTE ELLOS EN EL BLOQUE
BEGIN
    --CÓDIGO A EJECUTAR
EXCEPTION
    --MANEJO DE ERRORES

END;
/
*/
SET SERVEROUTPUT ON;

--TIPOS DE ERRORES
--1. PREDEFINIDOS (EJEMPLOS: ZERO_DIVIDE, TOO_MANY_ROWS, NO_DATA_FOUND...)
--EJEMPLO CON BLOQUE ANÓNIMO (BA):
DECLARE 
    V_FIRST EMPLOYEES.FIRST_NAME%TYPE;
    
BEGIN
    SELECT FIRST_NAME INTO V_FIRST
    FROM EMPLOYEES
    WHERE EMPLOYEE_ID = 1000;
    DBMS_OUTPUT.PUT_LINE('Empleado: ' || V_FIRST);
EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('No existe empleado con este ID');
END;
/

--2 EXCEPCIONES NO PREDEFINIDAS (POR EJEMPLO, violación de PK)
DECLARE
    JV_PK_VIOLATION EXCEPTION;
    PRAGMA EXCEPTION_INIT(JV_PK_VIOLATION, -1); --ASOCIADO A ORA-00001
BEGIN
    INSERT INTO JOBS VALUES ('AD_VP','Vice President', 10000, 15000);
EXCEPTION
    WHEN JV_PK_VIOLATION THEN
    DBMS_OUTPUT.PUT_LINE('Imposible introducir un JOB_ID que ya existe');
END;
/

--3 excepciones definidas por el usuario
declare
 v_sal employees.salary%type:=500;
 e_salario_bajo EXCEPTION;
begin
    IF V_SAL < 1000 THEN
    RAISE E_SALARIO_BAJO;
    END IF;
exception
    WHEN E_SALARIO_BAJO THEN
    DBMS_OUTPUT.PUT_LINE('El salario no puede ser inferior a 1000');
end;
/

--4-CREAR EXCEPCIONES PROPIAS ASOCIANDO UN CÓDIGO DE ERROR 0RA-XXXXX
/*
CÓDIGOS RESERVADOS PARA DEFINIR ERRORES
?20000 y ?20999
PASOS:
1. DECLARAR UNA EXCEPCIÓN PROPIA
2. ASOCIARLA AL NÚMERO ORA ELEGIDO
3. LANZAR EL ERROR CON RAISE_APPLICATION_ERROR(-20xxx, 'mensaje')
4. capturarlo en la sección EXCEPTION
*/

--EJEMPLO:
DECLARE
    VIDE EMPLOYEES.EMPLOYEE_ID%TYPE:=100;
    VSAL EMPLOYEES.SALARY%TYPE;
    ESAL_MIN EXCEPTION;
    PRAGMA EXCEPTION_INIT(ESAL_MIN, -20050);

BEGIN
    SELECT SALARY INTO VSAL
    FROM EMPLOYEES
    WHERE EMPLOYEE_ID = VIDE;
    
    VSAL:= 500;
    --DEFINIMOS UNA REGLA
    IF VSAL < 1000 THEN
    --LANZAR NUESTRO ERROR
    RAISE_APPLICATION_ERROR (-20050, 'El salario no puede ser inferior a 1000');
    end if;
    -- en caso de que no haya error, actualizamos con el salario indicado al empleado seleccionado
    UPDATE EMPLOYEES SET SALARY = VSAL
    WHERE EMPLOYEE_ID = VIDE;
    DBMS_OUTPUT.PUT_LINE('Salario del empleado actualizado correctamente. Use COMMIT para confirmar cambios.');

EXCEPTION
    when esal_min then 
    DBMS_OUTPUT.PUT_LINE('ERROR ORA-20050: Salario inferior al mínimo permitido, no se actualizará');
END;
/

--FINALMENTE REGISTRAR INFORMACIÓN DEL ERROR A TRAVÉS DE SQLCODE Y SQLERRM

--EJEMPLO:
BEGIN
UPDATE EMPLOYEES SET SALARY = SALARY / 0;

EXCEPTION
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('CÓDIGO DE ERROR: ' || SQLCODE);
    DBMS_OUTPUT.PUT_LINE('MENSAJE DE ERROR: ' || SQLERRM);

END;
/

--CUIDADO CON EL USO DE WHEN OTHERS