--entrega actividades PL/SQL
--NOMBRE DE SCRIPT (GUI�N) APELLIDO1_NOMBRE_ACT_PL_HR.sql
--USUARIO HR

--BLOQUE 1 - TRIGGER
--TRIGGER CONTROL DDE CAMBIOS EN TABLA DEPARTMENTS

-- PRIMERO SE CREA LA TABLA QUE ALMACENARA LOS CAMBIOS DE DEPARTMENTS
CREATE TABLE DEPT_LOG (OPERATION VARCHAR2(20),HORA_REALIZADA TIMESTAMP,OLD_DEPARTMENT_ID NUMBER(4),OLD_DEPARTMENT_NAME VARCHAR2(30),OLD_MANAGER_ID NUMBER(6),OLD_LOCATION_ID NUMBER(4),NEW_DEPARTMENT_ID NUMBER(4),NEW_DEPARTMENT_NAME VARCHAR2(30),NEW_MANAGER_ID NUMBER(6),NEW_LOCATION_ID NUMBER(4));

-- LUEGO SE CREA EL TRIGGER QUE MANEJARA CADA OPERACION REALIZADA DEPARTMENTS ANTES DE QUE SE PRODUZCA
CREATE OR REPLACE TRIGGER TR_DEPT_LOG BEFORE UPDATE OR INSERT OR DELETE ON DEPARTMENTS FOR EACH ROW
BEGIN
IF INSERTING THEN
    INSERT INTO DEPT_LOG VALUES('INSERT',SYSTIMESTAMP,NULL,NULL,NULL,NULL,:NEW.DEPARTMENT_ID,:NEW.DEPARTMENT_NAME,:NEW.MANAGER_ID,:NEW.LOCATION_ID);
END IF;

IF DELETING THEN
    INSERT INTO DEPT_LOG VALUES('DELETE',SYSTIMESTAMP,:OLD.DEPARTMENT_ID,:OLD.DEPARTMENT_NAME,:OLD.MANAGER_ID,:OLD.LOCATION_ID,NULL,NULL,NULL,NULL);
END IF;

IF UPDATING THEN
    INSERT INTO DEPT_LOG VALUES('UPDATE',SYSTIMESTAMP,:OLD.DEPARTMENT_ID,:OLD.DEPARTMENT_NAME,:OLD.MANAGER_ID,:OLD.LOCATION_ID,:NEW.DEPARTMENT_ID,:NEW.DEPARTMENT_NAME,:NEW.MANAGER_ID,:NEW.LOCATION_ID);
END IF;
END;
/

--BLOQUE 2 - bloques an�nimos

--2.1 sin capturar excepciones
--Obtener los datos de un �nico empleado (procedentes de una o varias tablas) solicitado por teclado
DECLARE
-- PRIMERO SE DECLARAN TODAS LAS VARIABLES QUE SE USARAN A CONTINUACION
EMP_ID NUMBER;
EMP_NAME VARCHAR2(30);
EMP_HIRE_DATE DATE;
EMP_SALARY NUMBER;
EMP_JOB VARCHAR2(30);
EMP_MANAGER_ID NUMBER;
EMP_MANAGER VARCHAR2(30);
EMP_DEPT VARCHAR2(30);

BEGIN
-- NADA MAS EMPEZAR PIDE POR TECLADO EL ID DE EMPLEADO DESEADO
EMP_ID := '&NOMBRE';
-- EN FUNCION DE ESE ID SE ALMACENAN EN EL RESTO DE VARIABLES LOS CAMPOS DE LA CONSULTA REALIZADA A CONTINUACION
SELECT E.FIRST_NAME ||' '|| E.LAST_NAME,E.HIRE_DATE,E.SALARY,
D.DEPARTMENT_NAME,J.JOB_TITLE,E.MANAGER_ID
INTO EMP_NAME,EMP_HIRE_DATE,EMP_SALARY,EMP_DEPT,EMP_JOB,EMP_MANAGER_ID 
FROM EMPLOYEES E INNER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID=D.DEPARTMENT_ID 
INNER JOIN JOBS J ON E.JOB_ID=J.JOB_ID WHERE EMPLOYEE_ID=EMP_ID;
-- EN ESTA OCASION ESCOGI ALMACENAR EL NOMBRE DEL MANAGER MEDIANTE UN SELECT ADICIONAL AUNQUE SE PODRIA HACER
-- MEDIANTE UN INNER JOIN ADICIONAL REFLEXIVO EN LA PRIMERA CONSULTA REFERENCIANDO EL EMPLOYEE_ID AL MANAGER_ID 
-- (... INNER JOIN EMPLOYEES M ON M.MANAGER_ID=E.EMPLOYEE_ID ...)
SELECT FIRST_NAME||' '||LAST_NAME 
INTO EMP_MANAGER 
FROM EMPLOYEES WHERE EMPLOYEE_ID=EMP_MANAGER_ID;
-- POR ULTIMO MOSTRAMOS POR PANTALLA UN MENSAJE QUE COMBINE TODAS LAS VARIABLES QUE HEMOS UTILIZADO
DBMS_OUTPUT.PUT_LINE('EL EMPLEADO CON ID '||EMP_ID||' TIENE COMO NOMBRE '||EMP_NAME||' Y FUE CONTRATADO EL '||EMP_HIRE_DATE||'. COBRA '||EMP_SALARY||'€ EN EL DEPARTAMENTO '||EMP_DEPT||', COMO '||EMP_JOB||' Y SU MANAGER ES '||EMP_MANAGER||'.');
END;
/


--2.2 con captura de excepciones
--obtener datos de varios empleados seg�n condiciones --> cursores expl�citos

DECLARE
-- Primero declaramos todas las variables donde almacenaremos los campos del cursor
DEPARTMENT DEPARTMENTS.DEPARTMENT_NAME%TYPE;

EMP_ID EMPLOYEES.EMPLOYEE_ID%TYPE;
EMP_NAME VARCHAR2(35);
EMP_HDATE EMPLOYEES.HIRE_DATE%TYPE;
EMP_MANAGER VARCHAR2(35);
EMP_JOB JOBS.JOB_TITLE%TYPE;
EMP_SALARY EMPLOYEES.SALARY%TYPE;
-- Luego declaramos el cursor que usaremos para asignar valores a las variables indicando como argumento el departamento que querramos
CURSOR EMP_DEPT(DEPI DEPARTMENTS.DEPARTMENT_NAME%TYPE) IS
SELECT E.EMPLOYEE_ID,E.FIRST_NAME||' '||E.LAST_NAME AS "NOMBRE",E.HIRE_DATE,E.SALARY,J.JOB_TITLE,M.FIRST_NAME||' '||M.LAST_NAME AS "MANAGER" 
FROM EMPLOYEES E INNER JOIN JOBS J ON E.JOB_ID=J.JOB_ID 
INNER JOIN EMPLOYEES M ON E.MANAGER_ID=M.EMPLOYEE_ID 
INNER JOIN DEPARTMENTS D ON D.DEPARTMENT_ID=E.DEPARTMENT_ID 
WHERE UPPER(D.DEPARTMENT_NAME)=UPPER(DEPI);

BEGIN
-- Pedimos el departamento por entrada de teclado
DEPARTMENT := '&DEPARTAMENTO';
-- Generamos la cabecera de la tabla
DBMS_OUTPUT.PUT_LINE(RPAD('+',101,'==')||'+');
DBMS_OUTPUT.PUT_LINE('| EMP_ID | '||RPAD('NOMBRE',20,' ')||'| HIREDATE | '||RPAD('SALARIO',8,' ')||'| '||RPAD('TRABAJO',25,' ')||'| '||RPAD('MANAGER',20,' ')||'|');
DBMS_OUTPUT.PUT_LINE(RPAD('+',9,'==')||RPAD('+',22,'==')||RPAD('+',11,'==')||RPAD('+',10,'==')||RPAD('+',27,'==')||RPAD('+',22,'==')||'+');
--Abrimos el cursor con la entrada por teclado como argumento y tambien un bucle en el que iremos imprimiendo el valor de cada registro y asignando un valor nuevo
--hasta que el cursor se quede sin registros.
OPEN EMP_DEPT(DEPARTMENT);
LOOP
FETCH EMP_DEPT INTO EMP_ID,EMP_NAME,EMP_HDATE,EMP_SALARY,EMP_JOB,EMP_MANAGER;
IF EMP_DEPT%NOTFOUND THEN
DBMS_OUTPUT.PUT_LINE(RPAD('+',101,'==')||'+');
END IF;
EXIT WHEN EMP_DEPT%NOTFOUND;
DBMS_OUTPUT.PUT_LINE('| '||EMP_ID||'    | '||RPAD(EMP_NAME,20,' ')||'| '||EMP_HDATE||' | '||RPAD(EMP_SALARY,8,' ')||'| '||RPAD(EMP_JOB,25,' ')||'| '||RPAD(EMP_MANAGER,20,' ')||'|');

END LOOP;
-- Importante cerrar siempre el cursor.
CLOSE EMP_DEPT;
-- Y por ultimo un bloque exception para que recoja cualquier excepcion que se produzca como una entrada por teclado inadecuada
EXCEPTION
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('HA OCURRIDO UN FALLO INESPERADO');
END;
/
--BLOQUE 3 - FUNCIONES
--3. Aumento o disminuci�n de salario

-- Primero declaramos la funcion con el salario, el porcentaje deseado y un char para indicar si hay que aumentar o reducir el salario
CREATE OR REPLACE FUNCTION SAL_ALTER(SAL NUMBER,INCREASE NUMBER,INCREMENTO VARCHAR2) RETURN NUMBER IS
BEGIN
-- si el varchar incremento es igual a true entonces devolvera la suma del salario y su porcentaje
    IF UPPER(INCREMENTO) = 'TRUE'  THEN
    RETURN SAL+SAL*(INCREASE/100);
    END IF;
-- en caso contrario devolvera la resta del salario y el porcentaje 
    RETURN SAL-SAL*(INCREASE/100);
END;
/

--BLOQUE 4 - PROCEDIMIENTOS
--3.1 Hace uso de la funci�n para cambiar salario de los empleados seg�n la funci�n
--solicitar� identificador de empleado
--solicitar� porcentaje de aumento o disminuci�n de salario
--aplicar� los cambios

-- Primero declaramos el procedimiento con el id del empleado que vamos a modificar, el porcentaje y un char para indicar si es un aumento o no
CREATE OR REPLACE PROCEDURE AUMENTO(EMP_ID INTEGER,PERCENTAGE NUMBER,AUMENTO VARCHAR2)
IS
-- Luego declaramos las variables que necesitemos como el nombre y el salario original junto que el modificado (realmente no es necesario)
    OLD_SALARIO NUMBER;
    NEW_SALARIO NUMBER;
    EMP_NAME VARCHAR(30);
BEGIN
-- En este select le asignamos al nombre y al salario antiguo sus valores
    SELECT SALARY,FIRST_NAME||' '||LAST_NAME INTO OLD_SALARIO,EMP_NAME FROM EMPLOYEES WHERE EMPLOYEE_ID=EMP_ID;
-- Hacemos uso de la funcion anterior para almacenar el aumento en la variable
    NEW_SALARIO := SAL_ALTER(OLD_SALARIO,PERCENTAGE,AUMENTO);
-- Actualizamos el registro
    UPDATE EMPLOYEES SET SALARY=NEW_SALARIO WHERE EMPLOYEE_ID=EMP_ID;
-- Imprimimos un mensaje orientativo para saber que cambios se han hecho
    DBMS_OUTPUT.PUT_LINE('EL SALARIO DEL EMPLEADO '||EMP_NAME||'('||EMP_ID||') HA SIDO ACTUALIZADO DE '||OLD_SALARIO||' A '||NEW_SALARIO||' EUROS.');
-- Por ultimo aplicamos los cambios mediante un commit
    COMMIT;
END;
/