SET SERVEROUTPUT ON;
SET VERIFY OFF;

DECLARE
    N1 NUMBER (2) := 2;
    N2 NUMBER (2) := 4;
    RESULTADO NUMBER;
BEGIN
    RESULTADO:=N1+N2;
    DBMS_OUTPUT.PUT_LINE(RESULTADO);
END;
/

DECLARE
    N1 NUMBER (2) := '&N1';
    OP CHAR(1) := '&OP';
    N2 NUMBER (2) := '&N2';
    RES NUMBER;
BEGIN
    CASE OP
        WHEN '+' THEN RES := N1+N2;
        WHEN '-' THEN RES := N1-N2;
        WHEN '*' THEN RES := N1*N2;
        WHEN '/' THEN RES := N1/N2;
    END CASE;

    DBMS_OUTPUT.PUT_LINE(RES);
EXCEPTION
        WHEN ZERO_DIVIDE THEN
            DBMS_OUTPUT.PUT_LINE('NO SE PUEDE DIVIDIR ENTRE 0');
    
END;
/

DECLARE
    N1 NUMBER (5) := &N1;
    N2 NUMBER (5) := &N2;
BEGIN

    IF N1 < N2 THEN 
        DBMS_OUTPUT.PUT_LINE('N2 - N1 = '||(N2-N1));
    ELSE
        DBMS_OUTPUT.PUT_LINE('N1 - N2 = '||(N1-N2));
    END IF;
        
END;
/
SELECT SAL FROM EMP WHERE MGR IS NULL;
SET SERVEROUTPUT ON;
DECLARE
    N1 NUMBER (5);
    N2 NUMBER (5) := &N2;
BEGIN
    SELECT SAL INTO N1 FROM EMP WHERE MGR IS NULL;
    IF N1 < N2 THEN 
        DBMS_OUTPUT.PUT_LINE('N2 - N1 = '||(N2-N1));
    ELSE
        DBMS_OUTPUT.PUT_LINE('N1 - N2 = '||(N1-N2));
    END IF;
        
END;
/
SELECT * FROM DEPT;
DECLARE
    NUMI EMP.SAL%TYPE := &N2;
BEGIN 
            DBMS_OUTPUT.PUT_LINE(RPAD('+ ',9,' ')||RPAD('EMPNO',10,' ')||RPAD('ENAME',10,' ')||'SAL');
    FOR REC IN (SELECT EMPNO,ENAME,SAL FROM EMP WHERE SAL >= NUMI) LOOP
            
            DBMS_OUTPUT.PUT_LINE(RPAD('+',35,'  ='));
            DBMS_OUTPUT.PUT_LINE(RPAD('|',9,' ')||RPAD(REC.EMPNO,10,' ')||RPAD(REC.ENAME,10,' ')||REC.SAL);
    END LOOP;
        
END;
/

DECLARE
    NUMI DEPT.DEPTNO%TYPE := &NUMI;
    NOMBRE DEPT.DNAME%TYPE;
BEGIN
    SELECT DNAME INTO NOMBRE FROM DEPT WHERE DEPTNO=NUMI;
    DBMS_OUTPUT.PUT_LINE('EL DEPARTAMENTO CON ID '||NUMI||' TIENE COMO NOMBRE '||NOMBRE);
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('NO SE HA ENCONTRADO UN DEPARTAMENTO'); 
END;
/

