/*
LENGUAJE PL/SQL ORACLE
--USUARIO HR Y SUS TABLAS
--BLOQUES ANÓNIMOS
--CURSORES
*/

--1.CURSORES IMPLÍCITOS

--PARA OPERACIONES SELECT INTO --> DEVUELVE UN ÚNICO VALOR (UNA FILA)
SET SERVEROUTPUT ON;
SET ECHO OFF;
SET VERIFY OFF;
--USUARIO HR
--1.1 A TRAVÉS DEL EMPLOYEE_ID, OBTENER EL FIRST_NAME Y JOB_TITLE (A TRAVÉS DE JOB_ID EN LA TABLA JOB)
DECLARE
 NUME EMPLOYEES.EMPLOYEE_ID%TYPE := '&ID';
 NOME EMPLOYEES.FIRST_NAME%TYPE;
 JOBE JOBS.JOB_TITLE%TYPE;
BEGIN
    SELECT E.FIRST_NAME, J.JOB_TITLE INTO NOME, JOBE
    FROM EMPLOYEES E
    INNER JOIN JOBS J
    ON E.JOB_ID=J.JOB_ID
    WHERE E.EMPLOYEE_ID = NUME;
    DBMS_OUTPUT.PUT_LINE('Empleado: ' ||nome ||' trabaja como ' || jobe);
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('El empleado '|| nume||' no existe.');
END;
/





--2.CURSORES EXPLÍCITOS
--deben ser declarados y se usan cuando un select devuelve varios registros
--pasos:
--1.declarar el cursor
--2.abrir el cursor
--3.recuperar cada fila que devuelva el cursor  (bucle)
--4.cerrar el cursor

--2.1
DECLARE
--DECLARACIÓN DEL CURSOR:
 CURSOR CU_EMP IS
 SELECT FIRST_NAME, SALARY FROM EMPLOYEES WHERE SALARY < 6000 ORDER BY SALARY DESC;
--DECLARACIÓN DE VARIABLES
 NE EMPLOYEES.FIRST_NAME%TYPE;
 SE EMPLOYEES.SALARY%TYPE;
BEGIN
 DBMS_OUTPUT.PUT_LINE('Empleados con sueldo inferior a 6000:');
 DBMS_OUTPUT.PUT_LINE('_____________________________________');
 DBMS_OUTPUT.PUT_LINE('');
 
 OPEN CU_EMP;
 LOOP
    FETCH CU_EMP INTO NE, SE;
    EXIT WHEN CU_EMP%NOTFOUND;
    DBMS_OUTPUT.PUT_LINE(RPAD(NE,15,' ') || LPAD(SE,10,' '));
 END LOOP;
CLOSE CU_EMP;
END;
/

--2.2 CURSOR EXPLÍCITO CON PARÁMETRO
DECLARE
--DECLARACIÓN DEL CURSOR:
 CURSOR CU_EMP(SAL NUMBER) IS
 SELECT FIRST_NAME, SALARY FROM EMPLOYEES WHERE SALARY < SAL ORDER BY SALARY DESC;
--DECLARACIÓN DE VARIABLES
 NE EMPLOYEES.FIRST_NAME%TYPE;
 SE EMPLOYEES.SALARY%TYPE;
BEGIN
 DBMS_OUTPUT.PUT_LINE('Empleados con sueldo inferior a: 4000');
 DBMS_OUTPUT.PUT_LINE('_____________________________________');
 DBMS_OUTPUT.PUT_LINE('');
 
 OPEN CU_EMP(4000);
 LOOP
    FETCH CU_EMP INTO NE, SE;
    EXIT WHEN CU_EMP%NOTFOUND;
    DBMS_OUTPUT.PUT_LINE(RPAD(NE,15,' ') || LPAD(SE,10,' '));
 END LOOP;
CLOSE CU_EMP;
END;
/

--BA PARA RECUPERAR VARIAS FILAS DE EMPLEADOS, ASOCIADAS A UN SALARIO INTRODUCIDO POR TECLADO
--excepción para cuando no haya registros con ese salario

DECLARE
--DECLARACIÓN DEL CURSOR:
 V_SAL EMPLOYEES.SALARY%TYPE:='&SALARIO';
 V_CONTADOR NUMBER:=0;
 CURSOR CU_EMP IS
 SELECT EMPLOYEE_ID, FIRST_NAME, SALARY FROM EMPLOYEES WHERE SALARY = V_SAL ORDER BY SALARY DESC;
--DECLARACIÓN DE VARIABLES
 NE EMPLOYEES.FIRST_NAME%TYPE;
 SE EMPLOYEES.SALARY%TYPE;
 EI EMPLOYEES.EMPLOYEE_ID%TYPE;
BEGIN
 DBMS_OUTPUT.PUT_LINE('Empleados con sueldo igual a : ' ||V_SAL);
 DBMS_OUTPUT.PUT_LINE('_____________________________________');
 DBMS_OUTPUT.PUT_LINE('');
 
 OPEN CU_EMP;
 LOOP
   
    FETCH CU_EMP INTO EI,NE, SE;
    EXIT WHEN CU_EMP%NOTFOUND;
     V_CONTADOR:=V_CONTADOR+1;
    DBMS_OUTPUT.PUT_LINE(RPAD(EI,8,' ')||RPAD(NE,15,' ') || LPAD(SE,10,' '));
 END LOOP;
    
CLOSE CU_EMP;
    IF V_CONTADOR = 0
    THEN 
        DBMS_OUTPUT.PUT_LINE('No hay empleados con salario: '||V_SAL);
    END IF;

END;
/
