--CREACIÓN DE CLAVES PRIMARIAS
--EL NOMBRE ASOCIADO A CADA RESTRICCION EMPIEZA POR PK_ Y LAS DOS PRIMERAS LETRAS DEL NOMBRE DE TABLA
-- 1. TABLA DEPT (CAMPO DEPTNO)



--2. TABLA EMP (CAMPO EMPNO)




--3. TABLA SALGRADE (CAMPO GRADE)




--4. TABLA BONUS
--AÑADIMOS CAMPO BONUSNO NUMBER(3) Y LO DESIGNAMOS COMO CLAVE PRIMARIA







--CREACIÓN DE CLAVES FORÁNEAS
--EL NOMBRE DE LA RESTRICCION EMPIEZA POR FK_ SEGUIDO DE LAS DOS PRIMERAS LETRAS DE LA TABLA_ 
--Y DOS PRIMERAS LETRAS DE LA TABLA REFERENCIADA
--5. TABLA EMP (EN SU CAMPO DEPTNO HACIENDO REFERENCIA AL CAMPO DEPTNO DE LA TABLA DEPT)





--6. TABLA BONUS (EN SU CAMPO ENAME HACIENDO REFERENCIA AL CAMPO ENAME DE LA TABLA EMP) 




--RESTRICCIONES TIPO CHECK
-- EL NOMBRE DE LAS RESTRICCIONES COMIENZA POR CH_ DOS PRIMEROS CARACTERES DEL NOMBRE DE LA TABLA_
--Y DOS PRIMEROS CARACTERES DEL NOMBRE DEL CAMPO

--7. TABLA EMP
--EL NUMERO EN EL CAMPO SAL DEBE ESTAR COMPRENDIDO ENTRE 700 Y 9999




--RESTRICCIONES DE TIPO UNIQUE
-- EL NOMBRE DE LAS RESTRICCIONES COMIENZA POR UN_ DOS PRIMEROS CARACTERES DEL NOMBRE DE LA TABLA_
--Y DOS PRIMEROS CARACTERES DEL NOMBRE DEL CAMPO
--8. TABLA DEPT (CAMPO DNAME)




--9. CREACIÓN DE LA VISTA PARA CONTROLAR LAS RESTRICCIONES DEL USUARIO SCOTT
--BUSCAR LOS CAMPOS DESEADOS EN LAS TABLAS USER_CONSTRAINTS Y USER CONS_COLUMNS






--10. CONSULTA PARA MOSTRAR NOMBRE DE LOS MANAGERS (TABLA EMP)





--11. CONSULTA PARA MOSTRAR LOS NOMBRES DE LOS EMPLEADOS CON ALIAS "EMPLEADO" 
--Y EN OTRA COLUMNA EL NOMBRE DE SU MANAGER CON EL ALIAS "MANAGER"




--12. CONSULTA PARA MOSTRAR LOS AÑOS QUE CUMPLIRAN EN LA EMPRESA EN 2023 TODOS LOS EMPLEADOS
--CALCULAR LOS AÑOS RESPECTO A SU FECHA DE ALTA (HIREDATE)




--13. AÑADIR  A LA TABLA EMP CAMPO ANYOS_ALTA
--TIPO NUMBER DE 2 DÍGITOS CON CONTENIDO A NULL




--14. MODIFICAR EL CONTENIDO DEL CAMPO ANYOS_ALTA
--CON EL NUMERO RESULTANTE DE LA OPERACION QUE LOS CALCULA RESPECTO A LA FECHA ACTUAL




--15. INSERTAR EN LA TABLA BONUS CON CLAVE PRIMARIA 1
--LOS DATOS EN ESA TABLA DEL EMPLEADO DE CATEGORÍA DE TRABAJO PRESIDENTE (CAMPO JOB EN TABLA EMP)