--1. crear tablas y restricciones
--tabla conductores
/*
CREATE TABLE N_TABLA (
CAMPO1 TIPO TAMAÑO [RESTRICCIONES],
...
CAMPON TIPO TAMAÑO RESTRICCIONES,
);

*/
CREATE TABLE CONDUCTORES (
    NIF CHAR (9) PRIMARY KEY, --1ª FORMA DE CREAR RESTRICCION (JUNTO AL NOMBRE DEL CAMPO)
    NOMBRE VARCHAR2 (20) NOT NULL,
    APELLIDO1 VARCHAR2 (15) NOT NULL,
    TIPO_PERMISO CHAR (1) NOT NULL,
    TELEFONO CHAR (9) NOT NULL,
    EMAIL VARCHAR2 (30) NOT NULL
);

--CATALOGOS ESPECIALES PARA EL USUARIO
--USER_TABLES
DESCRIBE CONDUCTORES;
DESCRIBE USER_TABLES;
SELECT TABLE_NAME FROM USER_TABLES;
--USER_CONSTRAINTS (MUESTRA RESTRICCIONES)

DESCRIBE USER_CONSTRAINTS;

SELECT * FROM USER_CONSTRAINTS;

SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME FROM USER_CONSTRAINTS;
--USER_CONS_COLUMNS
DESCRIBE USER_CONS_COLUMNS;

SELECT * FROM USER_CONS_COLUMNS;

--tabla vehiculos
CREATE TABLE VEHICULOS (
    MATRICULA CHAR (8) NOT NULL,
    MARCA VARCHAR2 (12) NOT NULL,
    MODELO VARCHAR2 (25) NOT NULL,
    CONSTRAINT PK_VE_MA PRIMARY KEY (MATRICULA) --2ªFORMA DE AÑADIR RESTRICCION (AL FINAL DE LOS CAMPOS CON PALABRA CLAVE CONSTRAINT)
);



--tabla conducir
CREATE TABLE CONDUCIR (
    NIF CHAR(9) NOT NULL,
    MATRICULA CHAR (8) NOT NULL,
    F_SALIDA DATE NOT NULL,
    F_ENTRADA DATE NOT NULL
);

--3ª FORMA DE AÑADIR RESTRICCIONES, CUANDO LA TABLA YA ESTÁ CREADA
--ALTER TABLE
/*(LAS TABLAS SE ALTERAN PARA:
    -AÑADIR MAS CAMPOS
    -CAMBIAR LA DEFINICION DE LOS CAMPOS
    -BORRAR CAMPOS
    -AÑADIR O MOIFICAR O BORRAR RESTRICCIONES)
*/


--2. modificar tablas

--AÑADIR A  TABLA CONDUCIR RESTRICCION DE PK
ALTER TABLE CONDUCIR ADD CONSTRAINT PK_CONDUCIR PRIMARY KEY (NIF,MATRICULA,F_SALIDA); 
--AÑADIR RESTRICCIONES DE FOREIGN KEY
ALTER TABLE  CONDUCIR ADD CONSTRAINT FK_NIF FOREIGN KEY (NIF) REFERENCES CONDUCTORES(NIF);

ALTER TABLE CONDUCIR ADD CONSTRAINT FK_MAT FOREIGN KEY (MATRICULA) REFERENCES VEHICULOS (MATRICULA);
--AÑADIR RESTRICCIONES DE TIPO CHECK
ALTER TABLE CONDUCIR ADD CONSTRAINT CH_FE_SAL CHECK (F_ENTRADA >= F_SALIDA); 

SELECT * FROM USER_CONSTRAINTS;
--AÑADIR RESTRICCION A LA TABLA CONDUCTORES, AL CAMPO TIPO_PERMISO
ALTER TABLE CONDUCTORES ADD CONSTRAINT CH_CO_TIPO_PER CHECK (TIPO_PERMISO IN ('A', 'B', 'C', 'D')); 

--3. borrar tablas

--CREAR TABLA DE PRUEBA
CREATE TABLE PRUEBA (HOLA NUMBER);
DROP TABLE PRUEBA;




-- 4. restricciones (al crear la tabla y después de haberla creado) (REFERENCIADO EN OPCIONES)