--CREAR USUARIO EMPRESARIO
--EMPRESA DE CONDUCTORES
--DROP USER EMPRESARIO;
CREATE USER EMPRESARIO IDENTIFIED BY "1234"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP"
QUOTA UNLIMITED ON "USERS";

--OTORGAR TODOS LOS PRIVILEGIOS
GRANT ALL PRIVILEGES TO EMPRESARIO;