--creación de tipos específicos de BDOR
--TIPOS DEFINIDOS POR EL USUARIO
--PUEDEN CONTENER ATRIBUTOS Y MÉTODOS 
--SINTAXIS:
CREATE TYPE DIRE_T AS OBJECT (
 CALLE VARCHAR2 (35),
 CIUDAD VARCHAR2 (20),
 CP NUMBER (5)
);
/

--TIPO EMPLEADO
CREATE TYPE EMP_T AS OBJECT (
 DNI VARCHAR2(9),
 NOMBRE VARCHAR2(50),
 SALARIO NUMBER,
 MEMBER FUNCTION SAL_ANUAL RETURN NUMBER
);
/

--CREACIÓN DEL CUERPO ASOCIADO AL MÉTODO
CREATE TYPE BODY EMP_T AS
 MEMBER FUNCTION SAL_ANUAL RETURN NUMBER IS
 BEGIN
  RETURN SALARIO *12;
 END;
END;
/

--COLECCIONES
--1._VARRAY (listas ordenadas de tamaño fijo)
CREATE TYPE TELEFONOS_T AS VARRAY(5) OF VARCHAR2(15);
/


--2._NESTED TABLE (se almacena en una tabla auxiliar, definir lista sin límite de tamaño)
CREATE TYPE AFICIONES_T AS TABLE OF VARCHAR2(30);
/

--CREACIÓN DE OBJETOS COMPLEJOS
--MODELAR ENTIDADES REALES COMBINANDO OBJETOS Y COLECCIONES
--TIPO PERSONA
CREATE TYPE PERSONA_T AS OBJECT(
 NOMBRE VARCHAR2(50),
 DIRECCION DIRE_T,
 TELEFONOS TELEFONOS_T,
 AFICIONES AFICIONES_T
);
/

--CREACIÓN DE TABLAS CON COLUMNAS QUE CONTIENEN OBJETOS
--CADA FILA REPRESENTA UN OBJETO EMP_T COMPLETO
CREATE TABLE EMP_OBJ OF EMP_T;
/

--TABLA RELACIONAL CON COLUMNA OBJETO
CREATE TABLE PEDIDOS (
 ID NUMBER PRIMARY KEY,
 FECHA DATE,
 DIRE_ENVIO DIRE_T
);
/

--TABLA CON COLECCIÓN
--PARA ALMACENAR LISTAS DINÁMICAS DE AFICIONES DE PERSONAS
CREATE TABLE PERSONAS OF PERSONA_T
 NESTED TABLE AFICIONES STORE AS AFICIONES_NT;
/

--INSERTAR OBJETO COMPLETO EN UNA TABLA DE OBJETOS
INSERT INTO EMP_OBJ
VALUES (EMP_T('12312323A','Thiago',1200));
/

--INSERTAR UN PEDIDO

INSERT INTO PEDIDOS (ID,FECHA, DIRE_ENVIO)
VALUES (1,SYSDATE,DIRE_T('Avda. América','Madrid',28009));/

--INSERTAR UN OBJETO COMPLEJO CON COLECCIONES
--INSERTAR PERSONAS:
INSERT INTO PERSONAS
VALUES (PERSONA_T('Ana',dire_t('Calle M','Badajoz',23001),
 TELEFONOS_T('999988888','111114444'),
 AFICIONES_T('Tenis','Fútbol')
));
/


--CONSULTAS
--CONSULTA DE ATRIBUTOS DE UN OBJETO
SELECT 
 P.ID,
 P.DIRE_ENVIO.CALLE,
 P.DIRE_ENVIO.CIUDAD,
 P.DIRE_ENVIO.CP
FROM PEDIDOS P;
/

SELECT 
 P.ID,
 P.DIRE_ENVIO.CP
FROM PEDIDOS P;
/
--CONSULTAR TABLA DE OBJETOS: POR EJEMPLO PARA LLAMAR A LOS MÉTODOS

SELECT
 E.NOMBRE,
 E.SALARIO,
 E.SAL_ANUAL()
FROM EMP_OBJ E;
/

--CONSULTAR COLECCIONES

-- CONSULTA DE AFICIONES (NESTED TABLE)
SELECT
 P.NOMBRE, T.COLUMN_VALUE AS AFICION
FROM PERSONAS P,
 TABLE (P.AFICIONES) T;
/


--CONSULTAS DE VARRAY
--ACCEDER A LA POSICIÓN DE ELEMENTO EN UN VARRAY
--SELECT TELEFONOS PENDIENTE REVISION
--acceso NO permitido A TRAVÉS DE posición del array
SELECT
 P.NOMBRE,
 P.TELEFONOS(1),
 P.TELEFONOS(2)
FROM PERSONAS P;
/
--alternativa para acceso al varray de telefonos
--mediante una subconsulta
SELECT VALUE(P).NOMBRE,
VALUE(P).DIRECCION.CIUDAD,
(SELECT T.COLUMN_VALUE FROM TABLE(VALUE(P).TELEFONOS) T WHERE ROWNUM = 1) AS PRIMER_TELEFONO
FROM PERSONAS P;
/

--CONTAR LOS TELEFONOS
SELECT P.NOMBRE,
COUNT(*) AS TOTAL_TELEFONOS
FROM PERSONAS P,
TABLE(P.TELEFONOS) T
GROUP BY P.NOMBRE;
/

--ACCESO A LOS TELEFONOS DE PERSONAS (CADA TELEFONO EN UNA FILA)
SELECT P.NOMBRE,
 T.COLUMN_VALUE AS TELEFONO,
 ROW_NUMBER() OVER (PARTITION BY P.NOMBRE ORDER BY ROWNUM) AS POSICION_NUMERO_TELEFONO
FROM PERSONAS P,
 TABLE(P.TELEFONOS) T;
/

--ACTUALIZACIÓN
--ATRIBUTO DE UN OBJETO
UPDATE EMP_OBJ E
SET E.SALARIO=E.SALARIO + 500
WHERE E.DNI = '12312323A';
/
COMMIT;


--OBJETO COMPLETO
--ACTUALIZAR DIRECCION DE ENVIO DE PEDIDOS
UPDATE PEDIDOS
SET DIRE_ENVIO = DIRE_T('Calle Nueva','Cáceres',34003)
where ID=1;
/

--BORRADO
--B1. BORRAR EN LA TABLA DE OBJETOS PERSONAS
DELETE FROM PERSONAS P
WHERE P.NOMBRE='Ana';
/
--desahacer cambios para seguir usando el registro de Ana
rollback;

--B2. BORRAR POR ATRIBUTO DE OBJETO ANIDADO (DIRECCION)
DELETE FROM PERSONAS P
WHERE P.DIRECCION.CIUDAD = 'Badajoz';
/

--B3. BORRAR POR CONTENIDO DE LA COLECCION NESTED TABLE (AFICIONES)
DELETE FROM PERSONAS P
WHERE 'Tenis' MEMBER OF AFICIONES;
/

--B4. TODAS LAS FILAS DE PERSONAS
DELETE FROM PERSONAS;
/

ROLLBACK;

--BORRADO DE OBJETOS:
--DROP
--IMPORTANTE EL ORDEN
/*
1. TABLAS
2. TYPE BODY
3. TIPOS OBJETO (OBJECT)
4. TIPOS COLECCIÓN (VARRAY / NESTED TABLE)
*/
--BORRAR TODO EN EL ORDEN CORRECTO
DROP TYPE DIRE_T;
/
--AL INTENTAR BORRAR UN TIPO, NO SE PODRÁ SI EXISTEN DEPENDENCIAS RESPECTO A ÉL
--ORDEN CORRECTO DE BORRADO DE TODOS LOS OBJETOS CREADOS

--1.- TABLAS
DROP TABLE PERSONAS;

DROP TABLE PEDIDOS;

DROP TABLE EMP_OBJ;

--2. BODY
DROP TYPE BODY EMP_T;

--3. TIPOS
DROP TYPE PERSONA_T;

DROP TYPE DIRE_T;

DROP TYPE EMP_T;

--4. COLECCIONES

DROP TYPE AFICIONES_T;

DROP TYPE TELEFONOS_T;



--CATÁLOGOS DEL DICCIONARIO DE DATOS:

