--BASES DE DATOS OBJETO RELACIONAL - BDOR
--RA7 DEL MÓDULO BBDD - DW1A
CREATE USER USEROBJETOS IDENTIFIED BY "1234"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP"
QUOTA UNLIMITED ON "USERS";

GRANT ALL PRIVILEGES TO USEROBJETOS;