--VISTAS DEL DICCIONARIO PARA VER OBJETOS CREADOS
--ACTIVIDAD:
--1. VOLVER A CREAR TODOS LOS OBJETOS (EJECUTAR INSERT TAMBIÉN)
--2. HACER USO DE LOS CATÁLOGOS INDICADOS A CONTINUACIÓN PARA MOSTRAR TODOS LOS OBJETOS (TIPOS, FUNCIONES, COLECCIONES...)
--3. DESCRIBE Y SELECT SOBRE CAMPOS QUE OS INTERESEN

--USER_TYPES


--USER_TYPE_ATTRS


--USER_TYPE_METHODS


--USER_TABLES


--USER_TAB_COLUMNS


--USER_NESTED_TABLES