--ÍNDICES:
--Estructura para mejorar la velocidad de las consultas SELECT
--PERMITE A ORACLE ENCONTRAR FILAS SIN NECDESIDAD DE RECORRER TODA LA TABLA
--TIPOS DE ÍNDICES:
--1. ÍNDICE AUTOMÁTICO (PK)

--2. ÍNDICE SIMPLE
--crear índice sobre cualquier columna --> que vaya a ser usada con frecuencia en select
CREATE INDEX IDX_EMP_ENAME ON EMP(ENAME); --COMO TIENE UNA RESTRICCIÓN UNIQUE SOBRE ENAME, YA ESTÁ EL ÍNDICE CREADO

--CREAR ÍNDICE SOBRE JOB DE LA TABLA EMP
CREATE INDEX IDX_EMP_JOB ON EMP(JOB);
--BÚSQUEDA TÍPICA QUE USA EL ÍNDICE:
SELECT * FROM EMP WHERE JOB='SALESMAN';

--3. ÍNDICE ÚNICO
--EVITAR VALORES DUPLICADOS EN COLUMNA
CREATE UNIQUE INDEX IDX_DEPT_DNAME ON DEPT(DNAME);

--USO EFICIENTE DEL ÍNDICE EN SELECT
SELECT * FROM DEPT WHERE DNAME='SALES';

--4. ÍNDICE COMPUESTO
CREATE INDEX IDX_EMP_DEPT_SAL ON EMP(DEPTNO,SAL);

--USO EFICIENTE:
SELECT * FROM EMP WHERE DEPTNO=10 AND SAL > 2000;

--5. ÍNDICES BASADOS EN FUNCIONES
--BÚSQUEDA DE NOMBRES EN MINÚSCULA
CREATE INDEX IDX_EMP_LOW_ENA ON EMP(LOWER(ENAME));

--OPTIMIZA CONSULTAS DE TIPO:
SELECT * FROM EMP WHERE LOWER(ENAME)='smith';

--VISTAS DEL DICCIONARIO DE DATOS PARA MOSTRAR ÍNDICES
--USER_INDEXES
--USER_IND_COLUMNS

DESCRIBE USER_INDEXES;

SELECT INDEX_NAME,INDEX_TYPE, TABLE_NAME 
FROM USER_INDEXES ORDER BY TABLE_NAME;

DESCRIBE USER_IND_COLUMNS;

SELECT * FROM USER_IND_COLUMNS ORDER BY TABLE_NAME;

--COMPROBAR EL USO DE ÍNDICE
--PRIMERO ESTAMOS COMPROBANDO RESULTADOS SOBRE CAMPOS NO INDEXADO
EXPLAIN PLAN FOR SELECT * FROM DEPT WHERE LOC='CHICAGO';

--ACCESO AL RESULTADO DE EXPLAIN
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);

--EN SEGUNDO LUGAR HACEMOS LO MISMO CON UN CAMPO INDEXADO, ASÍ PODREMOS COMPROBAR EL USO DE UN ÍNDICE EN SELECT
--EJEMPLO:
EXPLAIN PLAN FOR SELECT * FROM EMP WHERE ENAME='SCOTT';

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);

--BORRAR ÍNDICES:
DROP INDEX IDX_EMP_JOB;

COMMIT;