--COMENTARIO DE LINEA
/* COMENTARIO DE VARIAS
LINEAS
*/

--SENTENCIAS SELECT BÁSICAS SOBRE USUARIO HR

--LISTADO DE TABLAS DEL USUARIO ACTUAL
--CATÁLOGO USER_TABLES
DESCRIBE USER_TABLES;
SELECT TABLE_NAME FROM USER_TABLES;--OFRECE NOMBRE DE LAS TABLAS DEL USUARIO ACTUAL
--describir la estructura de una tabla
DESCRIBE COUNTRIES;
DESCRIBE EMPLOYEES;
SELECT * FROM COUNTRIES;

--SINTAXIS SELECT CAMPOS(SEPARADOS POR ,) FROM TABLA WHERE (CONDICIONES) GROUP BY ORDER BY
SELECT * FROM COUNTRIES  WHERE REGION_ID=1 OR REGION_ID=2 ORDER BY REGION_ID DESC;

--seleccionar el nombre (campo country_name) de la tabla countries
SELECT COUNTRY_NAME AS "NOMBRE DE PAÍS" FROM COUNTRIES;
--seleccionar todos los campos de la tabla countries
SELECT * FROM COUNTRIES;
--seleccionar todos los campos de la tabla countries ordenado el resultado por el contenido
--del campo region_id en orden descendente (z-a 0 9-0)
SELECT * FROM COUNTRIES ORDER BY REGION_ID DESC;
--selecciona los campos .... con la condición establecida con la cláusula where

--selecciona los campos indicados de la tabla countries con la condición
--el identificador del pais empiece con C más un caracter cualquiera _
SELECT * FROM COUNTRIES WHERE COUNTRY_ID LIKE 'C%' ORDER BY REGION_ID DESC;
--MODIFICACIONES SOBRE LA SENTENCIA ANTERIOR - FUNCIONES UPPER() Y LOWER()
SELECT * FROM COUNTRIES WHERE upper(COUNTRY_NAME) LIKE 'C%' ORDER BY REGION_ID DESC;
SELECT * FROM COUNTRIES WHERE LOWER(COUNTRY_NAME) LIKE '%i%' ORDER BY REGION_ID DESC;
--paises que pertenecen a la region 2
SELECT * FROM COUNTRIES WHERE REGION_ID=2;
--describimos la tabla de empleados
DESCRIBE EMPLOYEES;
--sueldos de empleados y su nombre
SELECT FIRST_NAME, SALARY FROM EMPLOYEES;

--sueldos de empleados (y su nombre) que ganen mas de 10000
SELECT FIRST_NAME, SALARY FROM EMPLOYEES WHERE SALARY > 10000;

--sueldos de empleados y su nombre que ganen menos de 10000 y mas de 6000 (ordenados order by campo asc ó desc)
SELECT FIRST_NAME, SALARY FROM EMPLOYEES WHERE SALARY <= 10000 AND SALARY >= 6000;

SELECT FIRST_NAME, SALARY FROM EMPLOYEES WHERE SALARY BETWEEN 6000 AND 10000;
--seleccionar nombre y fecha de alta de empleados
SELECT FIRST_NAME, HIRE_DATE FROM EMPLOYEES;
--empleados de alta en 2005 o después de ese año
SELECT FIRST_NAME, HIRE_DATE FROM EMPLOYEES WHERE HIRE_DATE >= '01-01-2005' ORDER BY HIRE_DATE DESC;
--USANDO EXTRACT YEAR FROM UNA FECHA
SELECT FIRST_NAME, HIRE_DATE FROM EMPLOYEES WHERE EXTRACT(YEAR FROM HIRE_DATE)>=2005; 

--USO DE AND/OR EN CLÁUSULA WHERE EN SENTENCIAS SELECT

--SUBCONSULTAS 
 SELECT FIRST_NAME, SALARY, PHONE_NUMBER FROM EMPLOYEES 
 WHERE SALARY > (SELECT SALARY FROM EMPLOYEES WHERE JOB_ID='AC_MGR' );

SELECT SALARY FROM EMPLOYEES WHERE JOB_ID='AC_MGR';

--CLÁUSULA BETWEEN EN WHERE
--EMPLEADOS CON SALARIO ENTRE 7000 Y 10000
SELECT * FROM EMPLOYEES WHERE SALARY BETWEEN 7000 AND 10000 ORDER BY SALARY DESC;

--CLÁUSULA IN, POR EJEMPLO EN WHERE
-- OBTENNER NOMBRE Y SALARIO DE EMPLEADOS CUYO SALARIO SEA 7000 10000 12000
-- CUANDO ES UN CONJUNTO LIMITADO DE VALORES USAMOS IN
SELECT FIRST_NAME, SALARY FROM EMPLOYEES WHERE SALARY IN (7000, 10000,12000) ORDER BY SALARY;

--EMPLEADOS CUYO DEPTO SEA 30, 60, 90 RESULTADO SON 14 EMPLEADOS
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID IN (30,60,90);

--DIFERENCIA CON BETWEEN ENTRE 30 Y 90 HAY 95 EMPLEADOS
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID BETWEEN 30 AND 90 ORDER BY DEPARTMENT_ID;

--ADELANTO DE CONSULTA COMPLEJA BUSCANDO DATOS EN DOS TABLAS
--GRACIAS A SU RELACIÓN CON FOREIGN KEY Y PRIMARY KEY

--OBTENER NOMBRE DE EMPLEADOS Y SU NOMBRE DE DEPARTAMENTO
SELECT E.FIRST_NAME, D.DEPARTMENT_NAME
FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;


--TABLA DE ORACLE DE NOMBRE DUAL - UTILIZABLE POR CUALQUIER USUARIO

DESCRIBE DUAL;

SELECT 7*98 FROM DUAL; --PERMITE IMPRIMIR EL RESULTADO DE LA OPERACIÓN MATEMÁTICA

SELECT SYSDATE FROM DUAL; --IMPRIME FECHA ACTUAL

SELECT UPPER('tengo sueño') FROM DUAL; --CONVIERTE A MAYÚSCULAS

SELECT EXTRACT (YEAR FROM SYSDATE) FROM DUAL;

SELECT EXTRACT (MONTH FROM SYSDATE) FROM DUAL;

SELECT EXTRACT (DAY FROM SYSDATE) FROM DUAL;