--OBTENEMOS LA MEDIA DEL SALARIO
SELECT ROUND(AVG(SALARY),0) AS "SALARIO MEDIO" FROM EMPLOYEES;

SELECT SUM(SALARY) AS "SUMA DE TODOS LOS SALARIOS" FROM EMPLOYEES;

SELECT ROUND(3.1416,3) FROM DUAL;

SELECT TRUNC(3.1416) FROM DUAL;

SELECT FLOOR(3.1416) FROM DUAL;

SELECT CEIL(3.1416) FROM DUAL;

--EMPLEADOS QUE GANEN MAS QUE LA MEDIA
SELECT * FROM EMPLOYEES WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES)ORDER BY SALARY;

--EMPLEADOS QUE GANEN MENOS QUE LA MEDIA
SELECT * FROM EMPLOYEES WHERE SALARY < (SELECT AVG(SALARY) FROM EMPLOYEES)ORDER BY SALARY;

--SALARIO MEDIO POR DEPARTAMENTOS (GROUP BY --> AGRUPAR)
SELECT FIRST_NAME, DEPARTMENT_ID FROM EMPLOYEES ORDER BY DEPARTMENT_ID;--PRUEBA

--SINTAXIS SELECT CAMPOS(SEPARADOS POR ,) FROM TABLA WHERE (CONDICIONES) GROUP BY  HAVING ... ORDER BY...


SELECT DEPARTMENT_ID, ROUND(AVG(SALARY),1) AS "SAL MEDIO POR DPTO" 
FROM EMPLOYEES GROUP BY DEPARTMENT_ID ORDER BY DEPARTMENT_ID;
--APLICANDO UNA SENTENCIA COMPLETA:
--SALARIO MEDIO POR DEPARTAMENTOS CUYO CÓDIGO SEA IGUAL O INFERIOR A 100 (GROUP BY --> AGRUPAR), CON MEDIA DE SALARIOS MAYOR O IGUAL A 5000
SELECT DEPARTMENT_ID, ROUND(AVG(SALARY),1) AS "SAL MEDIO POR DPTO" 
FROM EMPLOYEES WHERE DEPARTMENT_ID <= 100 GROUP BY DEPARTMENT_ID HAVING AVG(SALARY)>=5000 ORDER BY DEPARTMENT_ID;

SELECT COUNT(*) AS "EMPLEADOS POR DPTO.", DEPARTMENT_ID FROM EMPLOYEES GROUP BY DEPARTMENT_ID ORDER BY DEPARTMENT_ID; 

--TOTAL DE EMPLEADOS Y SALARIO MEDIO POR DEPARTAMENTO

SELECT DEPARTMENT_ID, COUNT(*) AS "EMPLEADOS POR DPTO.",ROUND(AVG(SALARY),1)
FROM EMPLOYEES GROUP BY DEPARTMENT_ID ORDER BY COUNT(*); -- USAR TAMBIEN EL ALIAS PARA ORDENR ORDER BY "EMPLEADOS POR DPTO."


--PARA NOTA: 
--LISTADO DE SALARIO MEDIO POR DEPARTAMENTO, PERO LO QUE APARECE ES NOMBRE DE DEPARTAMENTO EN LUGAR DEL ID
SELECT
ROUND(AVG(E.SALARY),1) AS "SAL MEDIO/DPTO",
D.DEPARTMENT_NAME AS "NOMBRE DPTO."
FROM DEPARTMENTS D
INNER JOIN EMPLOYEES E
ON D.DEPARTMENT_ID=E.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_NAME
ORDER BY "SAL MEDIO/DPTO" DESC;

--contar empleados que ocupan el mismo cargo (TABLA EMPLOYEES CAMPO JOB_ID)

SELECT JOB_ID, COUNT(EMPLOYEE_ID) AS "CANTIDAD DE EMPLEADOS"
FROM EMPLOYEES
GROUP BY JOB_ID ORDER BY "CANTIDAD DE EMPLEADOS" DESC;

--AGRUPAR Y APLICAR CONDICIÓN (GROUP BY CON HAVING )
--SACAR GRUPOS DE TRABAJO (JOB_ID) QUE TENGAN MÁS DE 5 EMPLEADOS
SELECT JOB_ID, COUNT(EMPLOYEE_ID) AS "CANTIDAD DE EMPLEADOS"
FROM EMPLOYEES
GROUP BY JOB_ID 
HAVING COUNT(*) > = 5
ORDER BY "CANTIDAD DE EMPLEADOS" DESC;


--RECUENTO DE EMPLADOS POR JOB_ID, PERO QUE SE AGRUPEN POR JOB_TITLE

SELECT J.JOB_ID, J.JOB_TITLE, COUNT(E.EMPLOYEE_ID) AS"EMP POR PUESTO"
FROM EMPLOYEES E
INNER JOIN JOBS J
ON E.JOB_ID=J.JOB_ID
GROUP BY J.JOB_ID , J.JOB_TITLE 
ORDER BY "EMP POR PUESTO" DESC;

--MODIFICAR LA SENTENCIA PARA CONCATENAR Y USAR GRUPOS POR EL RESULTADO CONCATENADO
SELECT J.JOB_ID ||' - ' || J.JOB_TITLE AS "PUESTO", COUNT(E.EMPLOYEE_ID) AS"EMP POR PUESTO"
FROM EMPLOYEES E
INNER JOIN JOBS J
ON E.JOB_ID=J.JOB_ID
GROUP BY  J.JOB_ID ||' - ' || J.JOB_TITLE
ORDER BY "EMP POR PUESTO" DESC;





--CONCATENAR
SELECT 'Hola' || ' Daniela' as "saludo" from dual; 
select concat('Hola', ' Daniela') as "saludo" from dual;
SELECT CONCAT ('X ',CONCAT ('Y',' Z')) FROM DUAL;

--GRUPOS DE TRABAJO CON SALARIO MEDIO
--TENIENDO QUE EL SALARIO MEDIO ES MAYOR A 5000
SELECT EM.JOB_ID, ROUND(AVG(SALARY),2)
AS "SALARIO MEDIO POR JOB"
FROM EMPLOYEES EM
GROUP BY EM.JOB_ID
HAVING AVG(SALARY) > 5000
ORDER BY "SALARIO MEDIO POR JOB";

--GRUPOS DE EMPLEADOS TENIENDO QUE EL SALARIO DEL GRUPO
--SEA MAYOR A LA MEDIA DE TODOS LOS SALARIOS (ENTRE MINIMOS Y MÁXIMOS)
SELECT EM.JOB_ID, ROUND(AVG(SALARY),2)
AS "SALARIO MEDIO POR JOB"
FROM EMPLOYEES EM
GROUP BY EM.JOB_ID
HAVING AVG(SALARY) >  
(SELECT AVG(SALARY) FROM EMPLOYEES) AND AVG(SALARY) 
BETWEEN (SELECT MIN(SALARY) FROM EMPLOYEES) AND (SELECT MAX(SALARY) FROM EMPLOYEES)--SUBCONSULTA
ORDER BY "SALARIO MEDIO POR JOB";


--CONSULTA MODIFICADA
SELECT EM.JOB_ID, ROUND(AVG(SALARY),2)
AS "SALARIO MEDIO POR JOB"
FROM EMPLOYEES EM
GROUP BY EM.JOB_ID
HAVING AVG(SALARY) <= --CALCULO DEL SALARIO MEDIO DE TODOS LOS JOBS  
--SELECT 
(SELECT ROUND((AVG(MAX_SALARY)+AVG(MIN_SALARY))/2,2) FROM JOBS);



--MEDIA DE LOS SALARIOS Y VALORES MÁXIMOS Y MÍNIMOS
SELECT ROUND(AVG(MAX_SALARY),2) AS "SALARIO MEDIO DE LOS MÁXIMOS", 
MIN(MIN_SALARY) AS "SALARIO MIN DE TODOS LOS MÍN", 
ROUND(AVG(MIN_SALARY),2) AS "MEDIA DE LOS MÍNIMOS", 
MAX(MAX_SALARY) AS "MAX DE TODOS LOS MÁX", 
ROUND((AVG(MAX_SALARY)+AVG(MIN_SALARY))/2,2) AS "AVG DE TODOS SAL EN JOB" FROM JOBS;

SELECT AVG(4,7) FROM DUAL; -- NO SE PUEDEN USAR DOS ARGUMDENTOS EN AVG --> INCORRECTO

SELECT (4+7)/2 FROM DUAL; --CÁLCULO DE LA MEDIA DE DOS CANTIDADES --> CORRECTO

--MEDIA DEL SALARIO PARA CADA JOB


SELECT (MAX_SALARY + MIN_SALARY)/2 FROM JOBS;


SELECT JOB_ID, JOB_TITLE, (MAX_SALARY + MIN_SALARY)/2 AS "SALARIO MEDIO POR EMPLEO" FROM JOBS;






--SELECT CON HIRE_DATE
SELECT TO_CHAR(HIRE_DATE, 'FM_Day') from employees;

















