--JOINS EMPLOYYES AND DEPARTMENTS
--1. JOIN O INNER JOIN
SELECT EMPLOYEES.EMPLOYEE_ID, EMPLOYEES.EMAIL, EMPLOYEES.FIRST_NAME, DEPARTMENTS.DEPARTMENT_ID, DEPARTMENT_NAME FROM EMPLOYEES INNER JOIN DEPARTMENTS
ON EMPLOYEES.DEPARTMENT_ID=DEPARTMENTS.DEPARTMENT_ID;

--VALORES SOBRE NULOS
--EMPLEADOS QUE NO SE LLEVAN PORCENTAJE DE COMISION
--EN EL CAMPO COMMISSION_PCT TENGA EL VALOR NULO/NO NULO
SELECT * FROM EMPLOYEES WHERE COMMISSION_PCT IS NULL; --IS NOT NULL PARA OBTENER LOS QUE SÍ TIENEN PORCENTAJE


SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID IS NOT NULL;


--2. LEFT JOIN
SELECT EMPLOYEES.EMPLOYEE_ID, EMPLOYEES.EMAIL, EMPLOYEES.FIRST_NAME, 
DEPARTMENTS.DEPARTMENT_ID, DEPARTMENT_NAME FROM EMPLOYEES 
LEFT JOIN DEPARTMENTS
ON EMPLOYEES.DEPARTMENT_ID=DEPARTMENTS.DEPARTMENT_ID;



--3. RIGHT JOIN
SELECT EMPLOYEES.EMPLOYEE_ID, EMPLOYEES.EMAIL, EMPLOYEES.FIRST_NAME, 
DEPARTMENTS.DEPARTMENT_ID, DEPARTMENT_NAME FROM EMPLOYEES 
RIGHT JOIN DEPARTMENTS
ON EMPLOYEES.DEPARTMENT_ID=DEPARTMENTS.DEPARTMENT_ID;



--4. FULL OUTHER JOIN

SELECT EMPLOYEES.EMPLOYEE_ID, EMPLOYEES.EMAIL, EMPLOYEES.FIRST_NAME, 
DEPARTMENTS.DEPARTMENT_ID, DEPARTMENT_NAME FROM EMPLOYEES 
FULL OUTER JOIN DEPARTMENTS
ON EMPLOYEES.DEPARTMENT_ID=DEPARTMENTS.DEPARTMENT_ID;

--JOINS CON MANAGER_ID (EN EMPLOYEES HACE REFERENCIA AL EMPLOYEE_ID)
--1. INNER JOIN

SELECT EM.FIRST_NAME AS EMPLEADO, MA.FIRST_NAME AS MANAGER
FROM EMPLOYEES EM
INNER JOIN EMPLOYEES MA
ON EM.MANAGER_ID=MA.EMPLOYEE_ID;

-- A CUANTOS EMPLEADOS DIRIGE CADA MANAGER (NOMBRE DEL MANAGER Y COLUMA CON RECUENTO DE EMPLEADOS)




--UNION (JOIN) DE TRES TABLAS
--LISTADO DE NOMBRES DE EMPLEADOS, CON SU NOMBRE DE DEPARTAMENTO Y NOMBRE DE JOB QUE OCUPA


