--USUARIO EMPRESARIO
--TRIGGER PARA MANEJAR LAS FECHAS DE SALIDA ENTRADA DE COCHES
SET SERVEROUTPUT ON;
SET ECHO OFF;
SET VERIFY OFF;
--RAISE_APPLICATION_ERROR(NUMERO,MENSAJE DE ERROR)
--NUMEROS QUE PUEDE USAR EL USUARIO PAR ADEFINIR SUS ERRORES -20000 y -20999
--MENSAJE, CADENA DE TEXTO DE HASTA 2048 Bytes

--trigger para que al insertar un nuevo registro en la tabla conducen
--la fecha de salida f_salida no pueda ser posterior a la fecha del día

CREATE OR REPLACE TRIGGER TR_F_SALIDA
BEFORE INSERT OR UPDATE OF F_SALIDA
ON CONDUCIR
FOR EACH ROW
BEGIN
    IF :NEW.F_SALIDA > SYSDATE THEN
    RAISE_APPLICATION_ERROR (-20001,'Fecha no válida');
    END IF;
END;
/

--PRUEBA CON INSERT
SET SERVEROUTPUT ON;
INSERT INTO CONDUCIR VALUES ('85698423O','7562-YRB','17/03/2026','18/03/2026');
--NO SE PUEDE EJECUTAR DEBIDO A LA RESTRICCIÓN INDICADA POR LA FECHA

--BLOQUE ANÓNIMO QUE BUSQUE LOS DATOS DE UN USUARIO(NIF) QUE SACÓ UN COCHE (MATRÍCULA)
--ACTUALIZAR FECHA DE ENTRADA Y FECHA DE SALIDA POR LA FECHA ACTUAL (SYSDATE)

DECLARE
 V_DNI CONDUCIR.NIF%TYPE:='85698423O';
 V_MAT CONDUCIR.MATRICULA%TYPE:='2395-JUF';
BEGIN
--UPDATE F_SALIDA Y F_ENTRADA CON LA FECHA ACTUAL PARA EL REGISTRO ENCONTRADO POR NIF Y MATRICULA
UPDATE CONDUCIR SET F_ENTRADA=SYSDATE,F_SALIDA=SYSDATE
WHERE NIF=V_DNI AND MATRICULA=V_MAT;
END;
/

DECLARE
    v_dni   CONDUCIR.NIF%TYPE      := '85698423O';
    v_mat   CONDUCIR.MATRICULA%TYPE := '2395-JUF';
    v_filas_actualizadas NUMBER;
BEGIN
    -- Actualizar fechas de entrada y salida
    UPDATE CONDUCIR
       SET F_ENTRADA = SYSDATE,
           F_SALIDA  = SYSDATE
     WHERE NIF = v_dni
       AND MATRICULA = v_mat;

    -- Guardar cuántas filas se han actualizado
    v_filas_actualizadas := SQL%ROWCOUNT;

    -- Mostrar resultado
    DBMS_OUTPUT.PUT_LINE('Filas actualizadas: ' || v_filas_actualizadas);

    -- Confirmar cambios
    COMMIT;
END;
/


ROLLBACK;

--CONVERTIR  EL ANTERIOR BA EN PA CON LA SOLICITUD DE LOS DOS DATOS, MATRICULA Y NIF POR TECLADO
CREATE OR REPLACE PROCEDURE PR_UP_CONDUCIR
IS
V_DNI CONDUCIR.NIF%TYPE:='&DNI';
V_MAT CONDUCIR.MATRICULA%TYPE:='&MATRICULA';
v_filas_actualizadas NUMBER;
BEGIN
--UPDATE F_SALIDA Y F_ENTRADA CON LA FECHA ACTUAL PARA EL REGISTRO ENCONTRADO POR NIF Y MATRICULA
UPDATE CONDUCIR SET F_ENTRADA=SYSDATE,F_SALIDA=SYSDATE
WHERE NIF=V_DNI AND MATRICULA=V_MAT;
-- Guardar cuántas filas se han actualizado
    v_filas_actualizadas := SQL%ROWCOUNT;
     -- Mostrar resultado
    DBMS_OUTPUT.PUT_LINE('Filas actualizadas: ' || v_filas_actualizadas);
    DBMS_OUTPUT.PUT_LINE('EJECUTE COMMIT PARA CONFIRMAR CAMBIOS O ROLLBACK PARA DESHACER');
END;
/

EXEC PR_UP_CONDUCIR;

--VERIFICAR

CREATE OR REPLACE PROCEDURE PR_UP_CONDUCIR
IS
    V_DNI  CONDUCIR.NIF%TYPE := '&DNI';
    V_MAT  CONDUCIR.MATRICULA%TYPE := '&MATRICULA';
BEGIN
    UPDATE CONDUCIR
       SET F_ENTRADA = SYSDATE,
           F_SALIDA  = SYSDATE
     WHERE NIF = V_DNI
       AND MATRICULA = V_MAT;
END;
/

CREATE OR REPLACE PROCEDURE PR_UP_CONDUCIR2
IS
    v_dni  CONDUCIR.NIF%TYPE;
    v_mat  CONDUCIR.MATRICULA%TYPE;
BEGIN
    -- Solicitar datos al ejecutar el procedimiento
    v_dni := '&DNI';
    v_mat := '&MATRICULA';

    UPDATE CONDUCIR
       SET F_ENTRADA = SYSDATE,
           F_SALIDA  = SYSDATE
     WHERE NIF = v_dni
       AND MATRICULA = v_mat;

    DBMS_OUTPUT.PUT_LINE('Filas actualizadas: ' || SQL%ROWCOUNT);

    COMMIT;
END;
/

EXEC PR_UP_CONDUCIR2;

--PROCEDIMIENTO CON PARÁMETROS QUE PEDIRÁ LOS DATOS AL SER EJECUTADO
CREATE OR REPLACE PROCEDURE PR_UP_CONDUCIR3 (
    p_dni IN CONDUCIR.NIF%TYPE,
    p_mat IN CONDUCIR.MATRICULA%TYPE
)
IS
BEGIN
    UPDATE CONDUCIR
       SET F_ENTRADA = SYSDATE,
           F_SALIDA  = SYSDATE
     WHERE NIF = p_dni
       AND MATRICULA = p_mat;

    DBMS_OUTPUT.PUT_LINE('Filas actualizadas: ' || SQL%ROWCOUNT);

    COMMIT;
END;
/

BEGIN
    PR_UP_CONDUCIR3('&DNI', '&MATRICULA');
END;
/

