--LENGUAJE PL/SQL DE ORACLE (PROGRAMACIÓN)
--TRIGGERS (DISPARADORES)

/*SINTAXIS DE TRIGGER
CREATE OR REPLACE TRIGGER nombreTrigger
cláusula de tiempo evento 
ON tabla
DECLARE declaraciones
BEGIN
instrucciones
EXCEPTION captura de excepciones
END;
*/

--ejemplos
--1. Controlar actualizaciones en la tabla SALGRADE
-- CADA VEZ QUE SE ACTUALICE ALGÚN DATO EN LA TABLA SALGRADE, SE INSERTARÁ UN REGISTRO DE CONTROL
-- EN UNA TABLA QUE CREAREMOS
CREATE TABLE CONTROL_SALGRADE (
USUARIO VARCHAR2(20),
FECHA TIMESTAMP,
MODIFICACION VARCHAR2(20)
);

--DISEÑO DEL TRIGGER
CREATE OR REPLACE TRIGGER TR_UP_SAL
BEFORE UPDATE
ON SALGRADE
BEGIN
    INSERT INTO CONTROL_SALGRADE VALUES (USER,SYSDATE,'MODIFICADO_SALGRADE');
END;
/

--CATÁLOGO PARA VER LOS DISPARADORES DE UN USUARIO USER_TRIGGERS
DESCRIBE USER_TRIGGERS;

SELECT TRIGGER_NAME,TRIGGER_TYPE, STATUS,TRIGGERING_EVENT, TABLE_NAME, TRIGGER_BODY FROM USER_TRIGGERS;

--CREAR VISTA PARA MOSTRAR LOS TRIGGERS DEL USUARIO ACTUAL
CREATE OR REPLACE VIEW V_TRG_SCOTT
AS
SELECT TRIGGER_NAME,TRIGGER_TYPE, STATUS,TRIGGERING_EVENT, 
TABLE_NAME, TRIGGER_BODY FROM USER_TRIGGERS
ORDER BY TABLE_NAME, TRIGGERING_EVENT;

--USO DE LA VISTA
SELECT * FROM V_TRG_SCOTT;

SELECT * FROM CONTROL_SALGRADE;



--PROBAMOS TRIGGER (ESTANDO INACTIVO NO SE EJECUTARÁ)
--SI BORRAMOS REGISTROS EN SALGRADE NO SE DISPARARÁ EL TRIGGER
DELETE SALGRADE WHERE GRADE=5;
ROLLBACK;



--ACTIVO EL TRIGGER Y VUELVO ALIMINAR REGISTRO GRADE=5 Y COMPRUEBO EL DISPARO
ALTER TRIGGER TR_DE_SAL ENABLE;

--PROBAMOS LA MODIFICACIÓN DE DATOS EN LA TABLA SALGRADE
--CAMBIAR EL HISAL DE GRADO 1 SERÁ 5000
UPDATE SALGRADE SET HISAL=5000 WHERE GRADE=5;
UPDATE SALGRADE SET LOSAL=1050 WHERE GRADE=1;
--CONFIRMAR CAMBIOS
COMMIT;

--ACTIVAR Y DESACTIVAR TRIGGERS
ALTER TRIGGER TR_UP_SAL DISABLE; -- DESACTIVAR
ALTER TRIGGER TR_UP_SAL ENABLE; -- ACTIVAR

--DESACTIVAR O ACTIVAR TODOS LOS TRIGGERS DEL USUARIO A LA VEZ (POR TABLA)
ALTER TABLE SALGRADE ENABLE ALL TRIGGERS;--ACTIVA TODOS LOS TRIGGERS ASOCIADOS A SALGRADE
ALTER TABLE SALGRADE DISABLE ALL TRIGGERS;--DESACTIVA TODOS LOS TRIGGERS ASOCIADOS A SALGRADE

--CREAR TRIGGER PARA QUE SE DISPARE UNA ACCIÓN (INSERTAR EN TABLA CONTROL_SALGRADE)
--DESPUÉS DE BORRAR REGISTROS EN SALGRADE

CREATE OR REPLACE TRIGGER TR_DE_SAL
AFTER DELETE
ON SALGRADE
DISABLE
BEGIN
    INSERT INTO CONTROL_SALGRADE VALUES (USER, SYSDATE, 'BORRADO_EN_SALGRADE');
END;
/

--TRIGGER PARA QUE DESPÚES DE INSERTAR REGISTROS EN SALGRADE SE DISPARE
--SI NO SE UTILIZA ENABLE (POR DEFECTO ESTARÁ ACTIVO)
CREATE OR REPLACE TRIGGER TR_IN_SAL
AFTER INSERT
ON SALGRADE
ENABLE
BEGIN
    INSERT INTO CONTROL_SALGRADE VALUES (USER, SYSDATE, 'INSERT_EN_SALGRADE');
END;
/

--PROBAMOS EL NUEVO TRIGGER
INSERT INTO SALGRADE VALUES (6,5001,8000);

SELECT * FROM CONTROL_SALGRADE;


--BORRAR TRIGGERS
--DROP TRIGGER NOMBRE_TRIGGER;