--TRIGGERS
--VALORES :NEW :OLD
--CADA VEZ QUE SE AUMENTE EL HISAL
--aparezca impreso en pantalla cual era el autiguo(antes de ser modificado)
--el nuevo valor

CREATE OR REPLACE TRIGGER TR_UP_HISAL
BEFORE UPDATE OF HISAL
ON SALGRADE
FOR EACH ROW
BEGIN

    DBMS_OUTPUT.PUT_LINE('Valores modificados:');
    DBMS_OUTPUT.PUT_LINE(:OLD.HISAL || '-->' || :NEW.HISAL);

END;
/

--PARA USAR IMPRESIÓN EN PROGRAMAS DE PL (DBMS_OUTPUT)
--SE NECESITA ACTIVAR UN SERVIDOR DE SALIDA PREVIAMENTE
SET SERVEROUTPUT ON; --OFF PARA DESACTIVAR

--UNA VEZ CREADO Y ACTIVO EL TRIGGER QUE ÚNICAMENTE IMPRIME POR PANTALLA
--SI TENEMOS EL SERVIDOR DE SALIDA SERVEROUTPUT ACTIVO
--AL MODIFICAR EL HISAL PARA ALGÚN REGISTRO DE LA TABLA SALGRADE
--SE DISPARARÁ (IMPRIMIENDO)

--PRUEBA DE MODIFICACIÓN DE HISAL
UPDATE SALGRADE SET HISAL=9000 WHERE GRADE=6;

UPDATE SALGRADE SET HISAL=9000;

--SOLO ERAN PRUEBAS-->DESHACER CAMBIOS :)
ROLLBACK;

--ACTIVIDAD TRIGGER
--CREACIÓN DE TRIGGER QUE SE DISPARE AL BORRAR UNA O VARIAS FILAS (REGISTROS) EN SALGRADE
--DE FORMA QUE SE GUARDEN LOS ANTIGUOS VALORES (GRADE, LOSAL Y HISAL)
--EN UNA TABLA LLAMADA SALGRADE_BORRADOS


--1. crear tabla con los campos que necesitemos
CREATE TABLE SALGRADE_BORRADOS (
    GRADE NUMBER,
    LOSAL NUMBER,
    HISAL NUMBER,
    FECHA_BORRADO TIMESTAMP
); 

--2. crear trigger
CREATE OR REPLACE TRIGGER TRG_SLG_DEL
AFTER DELETE ON SALGRADE
FOR EACH ROW
BEGIN
    DBMS_OUTPUT.PUT_LINE('Comprueba datos almacenados en SALGRADE_BORRADOS');
    INSERT INTO SALGRADE_BORRADOS VALUES(:OLD.GRADE, :OLD.LOSAL, :OLD.HISAL,SYSDATE);
END;
/

--comprobar que está activo

SELECT * FROM V_TRG_SCOTT;
--borrar uno o varios registros en salgrade para comprobar como se almacenan los datos en la nueva tabla de control de borrados
DELETE SALGRADE WHERE GRADE=5;

SELECT * FROM SALGRADE;
SELECT * FROM SALGRADE_BORRADOS;
DELETE SALGRADE;


--deshacer cambios para que no se borren los registros definitivamente de la tabla salgrade
ROLLBACK;
--dejar vacía la tabla SALGRADE_BORRADOS
TRUNCATE TABLE SALGRADE_BORRADOS; --BORRA DEFINITIVAMENTE

COMMIT;
