/*
SINTAXIS BÁSICA DE PROCEDIMIENTOS ALMACENADOS - PA
LENGUAJE PL/SQL
CREATE {OR REPLACE} PROCEDURE nombre_proc( param1 [IN | OUT | IN OUT] tipo,... )
IS [ó AS]
  -- Declaración de variables locales
  BEGIN
  -- Instrucciones de ejecución
  [EXCEPTION]
  -- Instrucciones de excepción
END;
/
*/


--borrado de procedimientos
--drop procedure nombre_proc;

--EJECUCIÓN DE PROCEDIMIENTO
--EXEC [o EXECUTE] NOMBRE_PROC;

--EJEMPLO 1. INTRODUCIR EN PROCEDIMIENTO PR_NE(ID_EM)
--AL SER EJECUTADO NOS MUESTRE EL NOMBRE DEL EMPLEADO CON EL ID BUSCADO E INTRODUCIDO COMO PARÁMETRO DEL PROCEDURE
--EXEC PR_NE(100); --> DEVUELVE Steven
CREATE OR REPLACE PROCEDURE PR_NE(PIDE IN EMPLOYEES.EMPLOYEE_ID%TYPE)
IS

 VNE EMPLOYEES.FIRST_NAME%TYPE;
BEGIN
    SELECT FIRST_NAME INTO VNE FROM EMPLOYEES WHERE EMPLOYEE_ID=PIDE;
    DBMS_OUTPUT.PUT_LINE('El empleado con ID '||PIDE||' es '||VNE);
EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('No existe empleado con ID: '||PIDE);
END;
/

SET SERVEROUTPUT ON;
--FORMAS DE EJECUTAR PA
--1 EXEC O EXECUTE
EXECUTE PR_NE(1110);

--2 BLOQUE ANÓNIMO PARA EJECUTAR UN PROCEDIMIENTO

BEGIN 
 PR_NE(143);
END;
/

--2. PROCEDIMIENTO PARA INTRODUCIR DOS VALORES(ENTEROS O DECIMALES) Y OBTENER EL PRODUCTO, SUMA RESTA Y DIVISIÓN IMPRESOS EN PANTALLA
/*
NÚMEROS INTRODUCIDOS: N1= y N2=
---------------------------------
SUMA:                       1234
RESTA:                        23
DIVISION:                   4.87
PRODUCTO:                6666666
*/

--VERSIÓN CON VARIABLES DECLARADAS PARA ENTEROS
CREATE OR REPLACE PROCEDURE PR_ARIT(N1 IN NUMBER, N2 IN NUMBER)
IS
    VN1 NUMBER:= N1;
    VN2 NUMBER:= N2;
    VS NUMBER := NULL;
    VR NUMBER := NULL;
    VP NUMBER := NULL;
    VD NUMBER := NULL;
BEGIN
    VS:= ROUND(VN1+VN2,0);
    VR:= ROUND(VN1-VN2,2);
    VP:= ROUND(VN1*VN2,2);
    VD:= ROUND(VN1/VN2,2);
    DBMS_OUTPUT.PUT_LINE('NÚMEROS INTRODUCIDOS: N1='||VN1|| ' y N2='||VN2);
    DBMS_OUTPUT.PUT_LINE('===================================');
    DBMS_OUTPUT.PUT_LINE(RPAD('SUMA: ',15,' ')|| LPAD(VS,20,' '));
    DBMS_OUTPUT.PUT_LINE(RPAD('RESTA: ',15,' ')|| LPAD(VR,20,' '));
    DBMS_OUTPUT.PUT_LINE(RPAD('PRODUCTO: ',15,' ')|| LPAD(VP,20,' '));
    DBMS_OUTPUT.PUT_LINE(RPAD('DIVISIÓN: ',15,' ')|| LPAD(VD,20,' '));
EXCEPTION
    WHEN ZERO_DIVIDE THEN
    DBMS_OUTPUT.PUT_LINE('ESTÁS INTENTANDO DIVIDIR ENTRE CERO');
END;
/


EXEC PR_ARIT(34,28);



