--PROCEDIMIENTOS CON CURSORES
--USUARIO HR
SET SERVEROUTPUT ON;

DECLARE
--DECLARACIÓN DEL CURSOR:
 CURSOR CU_EMP IS
 SELECT FIRST_NAME, SALARY FROM EMPLOYEES WHERE SALARY < 6000 ORDER BY SALARY DESC;
--DECLARACIÓN DE VARIABLES
 NE EMPLOYEES.FIRST_NAME%TYPE;
 SE EMPLOYEES.SALARY%TYPE;
BEGIN
 DBMS_OUTPUT.PUT_LINE('Empleados con sueldo inferior a 6000:');
 DBMS_OUTPUT.PUT_LINE('_____________________________________');
 DBMS_OUTPUT.PUT_LINE('');
 
 OPEN CU_EMP;
 LOOP
    FETCH CU_EMP INTO NE, SE;
    EXIT WHEN CU_EMP%NOTFOUND;
    DBMS_OUTPUT.PUT_LINE(RPAD(NE,15,' ') || LPAD(SE,10,' '));
 END LOOP;
CLOSE CU_EMP;
END;
/

--2.2 CURSOR EXPLÍCITO CON PARÁMETRO
--CREACIÓN DE PA PR_SALE(PSAL IN NUMBER) Y QUE DEVUELVA FIRST_NAME, EMAIL Y SALARY
--ADMITE UN PIN (parámetro de entrada) PARA SALARIO, Y DADO EL SALARIO, EL PA DEVUELVE DATOS DE EMPLEADOS QUE GANAN MENOS
--MISMO TIPO QUE UN CAMPO CONCRETO DE UNA TABLA TABLA.CAMPO%TYPE
--MISMO TIPO QUE CUALQUIER CAMPO DE UNA TABLA TABLA VX EMPLOYEES%ROWTYPE
--DBMS_OUTPUT.PUT_LINE('Nombre: '|| vx.first_name)

CREATE OR REPLACE PROCEDURE PR_SALE(PSAL IN NUMBER)
AS
 CURSOR CU_EMP IS
 SELECT * FROM EMPLOYEES WHERE SALARY < PSAL ORDER BY SALARY DESC;
--DECLARACIÓN DE VARIABLES
 /*NE EMPLOYEES.FIRST_NAME%TYPE;
 SE EMPLOYEES.SALARY%TYPE;
 */
 VE CU_EMP%ROWTYPE;
BEGIN
 DBMS_OUTPUT.PUT_LINE('Empleados con sueldo inferior a: ' ||PSAL);
 DBMS_OUTPUT.PUT_LINE('_____________________________________');
 DBMS_OUTPUT.PUT_LINE('');
 
 OPEN CU_EMP;
    
 LOOP
    FETCH CU_EMP INTO VE;
    EXIT WHEN CU_EMP%NOTFOUND;
    DBMS_OUTPUT.PUT_LINE(RPAD(VE.FIRST_NAME,15,' ') ||RPAD(VE.EMAIL,10,' ')|| LPAD(VE.SALARY,10,' '));
 END LOOP;
CLOSE CU_EMP;
END;
/

EXEC PR_SALE(3000);

DECLARE
 VS NUMBER := &SA;
BEGIN
PR_SALE(VS);
END;
/
